image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf false

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./GrobExp.Compiler.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GrobExp.Compiler.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release --filter TestCategory!=LongRunning ./GrobExp.Compiler.Tests/GrobExp.Compiler.Tests.csproj
